version: '3'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres-hotelm
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PW}
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - my-network
    volumes:
      - ./postgres_hotel:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

networks:
  my-network:
    driver: bridge